version: '3'
services:
  database:
    image: mongo:latest
    container_name: 3mop_database
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - database_data:/data/db

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    container_name: 3mop_api
    depends_on:
      - database
    ports:
      - ${APP_PORT}:4000
    environment:
      - DATABASE_URL=mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}
    volumes:
      - .:/usr/src/app

volumes:
  database_data:
